### PR TITLE
Make sure autoHeight attr is only applied on init #67

### LINKED ISSUE #67: Autoheight gets applied to the wrong items
autoheight-bug

## Solution

The problem is due to the [cloneItems method](https://github.com/uberVU/grid/blob/318753550bc5e9600aadf44b981787712c5e6229/src/gridList.js#L57-L79). When the properties are [copied](https://github.com/uberVU/grid/blob/318753550bc5e9600aadf44b981787712c5e6229/src/gridList.js#L74-L76) from the source to the destination we don't take into account any properties existing only on the destination.

So what happens is this:

1. Grid initializes, auto size attribute is applied to items.
2. Snapshot.
3. Drag and drop. At this point the order of the items might have changed.
4. Snapshot is copied back. Now the auto size attribute may be copied to the wrong items.
5. Multiple items end up with the auto size attribute.
6. Resize -> items end up being stretched.

A solution is to clear the extra properties on the destination. We can do this by doing two iterations over the properties:

- once on the source where we copy them over the destination,
- once on the destination where we copy them **from** the source.

The second time will set any extra properties to `undefined` since they won't be on the source object.

Another solution is to ignore the auto size attribute when copying the properties since it's the only extra property that we add onto the items.

### PR DESCRIPTION
**Pull request by ovidiu-chereches-hs**
Fixes #67

> - We need this function to be called later on in order to apply the
current number of lanes to the “flexible” item attr, but setting the
autoHeight field itself is only done once!
- In order to make sure autoHeight is never set after the first call,
we only set it when the attr is undefined, and set a boolean value in
either true or false case

### CODE REVIEW

File: src/gridList.js [hunk 1]
```diff
@@ -254,11 +254,12 @@ GridList.prototype = {
...
-    var changedItems = [],
-        i,
-        item;
-    for (i = 0; i < initialItems.length; i++) {
-      item = this._getItemByAttribute(idAttribute, initialItems[i][idAttribute]);
+    var changedItems = [];
+
+    for (var i = 0; i < initialItems.length; i++) {
+      var item = this._getItemByAttribute(idAttribute,
+                                      initialItems[i][idAttribute]);
```
Comment (ovidiu-chereches-hs) [inline src/gridList.js]: Fix indentation

**Comment by ovidiu-chereches-hs** [comment]
LGTM
